name: Build pipeline

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

 
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      cat /etc/docker/daemon.json
      echo "restart docker..."
      sudo systemctl daemon-reload
      sudo systemctl restart docker
      docker login  http://40.76.167.146:80 -u admin -p  Harbor12345




      
     
  