name: Build pipeline

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

 
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-dev-subscription'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'docker login  40.76.167.146:80 -u admin -p Harbor12345'

      
     
  