name: Build pipeline

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

 
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
      docker login  40.76.167.146:80 -u admin -p  Harbor12345


      
     
  