
name: Build pipeline
# Build Pipeline 
# Docker Build the app code using Azure Devops Resoures

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

- task: Docker@2
  inputs:
    containerRegistry: 'connection to DevHarbor Container Registry'
    repository: 'nqcc'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'