name: Build pipeline

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

 
variables:
  HELM_EXPERIMENTAL_OCI: 1
  registryName: '40.76.167.146'
  BuildId: '$(Build.BuildId)'
  tag: '$(Build.BuildId)'
  reponame: '$(Build.Repository.Name)'


steps:

- task: Bash@3
  name: 'Docker_login_Harbor'
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      cat /etc/docker/daemon.json
      echo '{ "exec-opts": ["native.cgroupdriver=cgroupfs"], "insecure-registries": ["0.0.0.0/0"] }' | sudo tee /etc/docker/daemon.json
      echo "restart docker..."
      cat /etc/docker/daemon.json
      sudo systemctl daemon-reload
      sudo systemctl restart docker
      docker login 40.76.167.146:80 -u admin -p  $(harbor-passwd)


- task: Bash@3
  name: 'Docker_build' 
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      second_half_name=$(echo $(reponame) | cut -d'/' -f2)
      docker build -t $(registryName)/nqcc/$(second_half_name):$(BuildID) .
      docker images  
      echo 'Build Success!'
    #workingDirectory: '$(Build.SourcesDirectory)/AppA.WebApi'


  
     
  