stages:
- stage: ExampleStage
  jobs:
  - job: Job1
    displayName: 'Job 1'
    pool:
      vmImage: 'windows-latest'

    steps:
    - script: |
        echo "##vso[task.setvariable variable=variableFromJob1]$variableFromJob1"
      displayName: 'Set Output Variable'

  - job: Job2
    displayName: 'Job 2'
    dependsOn: Job1
    pool:
      vmImage: 'windows-latest'

    steps:
    - script: |
        echo "Variable from Job 1: $(variableFromJob1)"
      displayName: 'Use Output Variable'