name: Build pipeline

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'connection to DevHarbor Container Registry'
        repository: 'nqcc'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
