name: Build pipeline

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables: 
  registry_password: $(registry_password)

# stages:
# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     steps:
#     - task: Docker@2
#       inputs:
#         containerRegistry: 'connection to DevHarbor Container Registry'
#         repository: 'nqcc'
#         command: 'buildAndPush'
#         Dockerfile: '**/Dockerfile'
 
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-dev-subscription'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'docker login  40.76.167.146:80 -u admin -p $(registry_password)

      
     
  